const char index_html[] PROGMEM = R"rawliteral(
"<!-- index.html -->\n"
"<!DOCTYPE html>\n"
"<html>\n"
"  <head>\n"
"    <title>ESP32 Web Server</title>\n"
"    <style>\n"
"      body { font-family: Arial; text-align: center; }\n"
"      button { padding: 10px; background-color: #007BFF; color: white; border: none; cursor: pointer; }\n"
"      button:hover { background-color: #0056b3; }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <h1>ESP32 Web Server</h1>\n"
"    <p>LED State: <span id=\"ledState\">OFF</span></p>\n"
"    <button onclick=\"toggleLED()\">Toggle LED</button>\n"
"    <script>\n"
"      function toggleLED() {\n"
"        var xhr = new XMLHttpRequest();\n"
"        xhr.open('GET', '/toggle', true);\n"
"        xhr.onreadystatechange = function() {\n"
"          if (xhr.readyState == 4 && xhr.status == 200) {\n"
"            document.getElementById('ledState').innerHTML = xhr.responseText;\n"
"          }\n"
"        };\n"
"        xhr.send();\n"
"      }\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
"
)rawliteral";
